version: "3.9"

services:
  postgres:
    # image: integratedaisolutions/postgres-pgvector:latest #myuser/pgvector #postgres:
    image: postgres:16-alpine #postgres:
    environment:
      - POSTGRES_DB=postgres # optional
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      # bound mount volume. data folder will be created in project
      - ./db-data/:/var/lib/postgresql/data/

  pg-admin:
    # image: dpage/pgadmin4:latest
    image: tobi312/pgadmin4:6.5
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/
    ports:
      - "5050:5050"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  data:
    name: data
