services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    develop:
      watch:
        - path: app/
          target: /app
          action: sync
 
  
