

FROM python:3.8.10-slim-buster as dev

WORKDIR /app
RUN touch /app/test.txt
RUN echo "hello" > /app/test.txt


FROM python:3.8.10-slim-buster

WORKDIR /app

COPY requirements.txt /app

RUN pip install -r requirements.txt

COPY --from=dev app/test.txt /app

COPY . /app


