version: "3.8"
services:
  app:
    build: . # for local development
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: >
      sh -c "python manage.py makemigrations && \
             python manage.py migrate && \
             python manage.py migrate && \
             echo "==================" && \
             echo 'Django Version:' && \
             echo "==================" && \
             django-admin --version \
             echo "==================" && \
             python manage.py runserver 0.0.0.0:8000"

